name: content-demo-microk8s
version: 'latest'
summary: Snap showing how to use the configuration launcher in MicroK8s.
description: |
  Snap a demo configuration yaml file that MicroK8s can apply.
base: core20

grade: stable
confinement: strict

slots:
  configuration:
    interface: content
    content: configuration
    source:
      read:
        - $SNAP/launcher

parts:
  configuration:
    plugin: dump
    source: launcher
